### ISSUE TITLE
Changing the default matching algorithm

### ISSUE THREAD

**Issue by swarn** [nvim-lua/telescope.nvim#178]
I see that the default sorting method is Levenshtein distance, and that a project goal is to enable other sorters.

I like the [fzy](https://github.com/jhawthorn/fzy) matching algorithm enough that I [implemented it in lua](https://github.com/swarn/fzy-lua). Would you be interested in a pull request that replaces Levenshtein with fzy's algorithm as the default `telescope` sorter?

**Comment by tjdevries** [comment]
Ah, I can see why you'd think the default impl is levenshtein, but it's actually a custom one right now.

Even so, having an fzy sorter builtin would be really cool! I checked out the project and it's awesome. 

You can start the PR and I will take a look at it. I can build some configuration options and a few other things that would make it a lot easier for people to switch to using the fzy style as the default sorting. 

One of the big goals of the project was that people should be able to configure each aspect of the fuzzy finding experience, including fuzzy finding algorithms 😁 so that sounds great. 

Do you need any help from me on where to start?

**Comment by swarn** [comment]
Ah yes, I see now that Levenshtein is hanging out at the bottom of `sorters.lua`. I hadn't looked too closely at it yet—I wanted to make sure you'd be interested. The basic changes seem to be:

- Some indirection on the default sorter. One of:
  1. The calls to `sorters.get_generic_fuzzy_sorter` everywhere are replaced with e.g. `sorters.get_default_sorter`, which is a factory that returns `get_generic_fuzzy_sorter()` or another sorter as described below.
  2. turn `get_generic_fuzzy_sorter` into the factory and factor the current sorter definition out of it and into another function. Much more localized change, but *maybe* more awkward.
- For now, probably add just a single global variable `g:telescope_default_sorter` with `original` (default) and `fzy` values, read by the factory function.
- Do whatever impedance matching is needed to make the `fzy` interface match the `Sorter` interface.

Does that sound about right?

**Comment by tjdevries** [comment]
I can manage the configuration stuff, since what you said doesn't quite fit what I was thinking. For now, making a Sorter that uses the fzy algorithm you made would be good as a first step.

After that, we can chat more in the pr

**Comment by tjdevries** [comment]
(btw, I just had a baby boy, so I may be slow on some of the review, just depends on my days 😂)

**Comment by ccaseiro** [comment]
congratulations.
yes ... you will slow a little in the next few days :)

**Comment by swarn** [comment]
First, congratulations on your baby!

Second, thanks for your neovim work. I just switched to using 5.0 and the neovim lsp; I'm really liking it.

What you said sounds good; I'll just add the Sorter and send you a PR.
