### ISSUE TITLE
Error while calling lua chunk

### ISSUE THREAD

**Issue by jsatk** [nvim-lua/telescope.nvim#221]
```
E5105: Error while calling lua chunk: ...tk/.vim/plugged/telescope.nvim/lua/telescope/builtin.lua:14: attempt to index field 'fn' (a nil value)
```

Just installed via the README instructions and instantly got this error on my first usage.

**Comment by Conni2461** [comment]
Hey it looks like you are not using neovim nightly, which is a prerequisite since lua is not available in the current stable (v0.4.4) version. But just to be sure, can you say which `command` you executed and what `nvim -v` returns.
@tjdevries We should probably run the version check in vimL, because it should not run for people with a neovim version < 0.5.

**Comment by jsatk** [comment]
@Conni2461 ah. My apologize. I was actually watching TJ stream last night and was impressed by this tool so went to try it out. I must've glazed over the "nightly" requirement. 

Will close.

**Comment by tami5** [comment]
@jsatk checkout my pr for telescope's new docs, it a draft but you will get better idea #216

**Comment by Hawkjack1729** [comment]
Can u please help me solving this issue
![image](https://user-images.githubusercontent.com/93283573/193440379-e128ac56-9d4c-47b8-9d80-e1ad9afcf799.png)

**Comment by tjdevries** [comment]
looks like you haven't installed the media files extension.

**Comment by Hawkjack1729** [comment]
Thank you for your response.Telescope is a very good extension and i like
it very much.
