### ISSUE TITLE
High memory usage when finding files.

### ISSUE THREAD

**Issue by chrisburgin95** [nvim-lua/telescope.nvim#81]
When using `git_files` for `find_files` I am noticing large jumps in memory usage that is not released.

### How To Replicate
1. Start nvim. Check the memory usage, mine sits below 20 normally.
2. Use one of the above functions but do not type anything. Memory usage should stay normal.
3. Search for something, memory usage will spike.

**Comment by tjdevries** [comment]
Can you define "spike"? 

And then even after the usage, the memory is not freed? Does it continue to increase?

Thanks for the report :smile:

**Comment by chrisburgin95** [comment]
I should pay more attention when I file these issues!

It’s a larger project. With git_files I jump up to near 200mb. With find_files it’s near 400mb. The memory usage does not decrease once I stop using the above functions, stays high. 

I can post more details about my setup tomorrow if needed.

**Comment by tjdevries** [comment]
Very interesting.

When you say "large" can you give me an approximate size?

Obviously we shouldn't be leaving memory sitting around, but I'm also just trying to get a grasp of the size. We do use some caches to make fuzzy finding faster after repeated attempts, but 200 mb seems kind of huge... :laughing: 

Thanks.

**Comment by Luxed** [comment]
I can confirm this issue, on my usual 10k files project, I get ~5mb more every time I open `find_files` and ~1mb if I open `buffers`.
I verified this by using `pmap $(pgrep nvim)`.
The memory is never freed. But it also doesn't increase progressively, only when you start telescope.

Even for me, 5mb at a time seems low, but since my neovim instance stays open all day, this can add up to a few hundred mb at the end of the day.

**Comment by chrisburgin95** [comment]
The project is 9k files large. 

Like @Luxed it is happening every time i open `find_files`, instead of seeing a 1mb jump I am seeing a ~30mb jump. Searching for the same thing over and over leads to the same increase as searching for something new each time. Also same as @Luxed the memory is never freed.

**Comment by tjdevries** [comment]
Related: #83

(I'm investigating more reasons why this could be happening).

Thanks again for reporting!

**Comment by chrisburgin95** [comment]
Probably not super helpful but might be worth noting just in case. 

I recently switched from MacOS to Fedora this week and I am having the same issue with a fresh setup.

**Comment by tjdevries** [comment]
Thanks for the update. I haven't been able to track it down, but I am working towards it by doing some other performance / memory monitoring & enhancements.

Hopefully I can track it down at some point :laughing: 

In the mean time, I have found several other performance and memory improvements (and will continue to do so).

**Comment by tjdevries** [comment]
OK, I just pushed an update that might minimize this problem. I don't think I've tracked down _everything_ but I do think I made some serious progress on it. We do use some caching so that larger searches can be faster over time, so you may still see some memory growth over time, but hopefully it is much smaller than before.

You'll want at least an updated telescope & plenary, possibly an updated nvim :)

Let me know what you all find out!

**Comment by chrisburgin95** [comment]
@tjdevries Seems to be working great! When I use `Git Files` it jumps up to ~800mb of memory usage but when I close the popup memory usage drops back down to a more reasonable level near 125mb. It does seem like quite a bit of memory even for a cache, but its a level I am more than happy with!

Thanks so much for all the work on this issue!! I have been using telescope at work for a month or so now and its excellent!

**Comment by tjdevries** [comment]
Awesome :)

Just out of curiosity, can you tell me how many files are in your git repo?

`git ls-files | wc -l`

I do have some other longer term memory improvements I want to make (like not storing as many strings, things like that) but I didn't want to work on those if we leaked memory infinitely anyway :laughing:

**Comment by tjdevries** [comment]
I just pushed some changes that should _hopefully_ reduce memory usage for you -- It seemed to for me by a decent amount.

Could you try again for me and see if you're still getting such high usage?

**Comment by chrisburgin95** [comment]
It has just under 9,000 files.

Looks like the update reduced memory usage when finding by about 50%!!

**Comment by tjdevries** [comment]
:+1: awesome. 

We can try and find some more ways over time to limit the memory, but I think this is pretty good.

`9000 files * (maybe something like) 50 characters = 450,000 characters alone` means we're going to definitely be having some amount of memory jump when searching :) glad I was able to make it much smaller though!

**Comment by Luxed** [comment]
Yeah, it's mostly fixed for me, maybe under 1mb every time, but that's nothing.
The weird thing though is that my project has around 9000 files too. But the initial cost is only a few mb, not a few _hundred_ mb.

**Comment by chrisburgin95** [comment]
@Luxed Later today, or tomorrow, I'll try a fresh config with just telescope and see if maybe something else in mine is causing it to balloon quickly. The project I work on is deeply nested and thus the file paths are very long, wonder if that could be a contributing factor?

**Comment by tjdevries** [comment]
More letters = more memory :laughing: but yeah, we'll try and prune it down more over time. At some point, I will try and build some test harness or something that can monitor max memory at least so that I can try and make sure we never release anything that obviously 10x the memory usage or something :laughing: 

(btw, Is this OK to close now?)

**Comment by chrisburgin95** [comment]
I think very good to close! Thanks!
